import type { Metadata } from "next";
import dynamic from "next/dynamic";

const Width = dynamic(() => import('@/components/width'), {ssr: true});

export const metadata: Metadata = {
  title: "About - Studies - Next.Js",
  description: "Generated by create next app",
  keywords: "test, teste"
};

export default function AboutPage() {
    return (
        <>
            <div>
                <h2>About</h2>
                <Width />
            </div>
        </>
    )
}